# Generated by Django 2.2.8 on 2020-06-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street',
            new_name='road',
        ),
    ]
