# Generated by Django 2.2.8 on 2020-06-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200605_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='road',
        ),
    ]
